parameters:
- name: deploy
  displayName: Deloy Buildartifact
  type: boolean
  default: false

trigger:
  branches:
    include:
      - master

pool:
  vimImage: ubuntu-latest

stages:
- stage: build_test
  displayName: Build Image
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: ./eclipse-mosquitto/Dockerfile