parameters:
- name: deploy
  displayName: Deloy Buildartifact
  type: boolean
  default: false

variables:
  remoteProjectPath: /home/felix/projects/mqtt_broker
  sshEndpoint: 71430-33034
  dockerfile: ./eclipse-mosquitto/Dockerfile

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy
  condition: eq('${{ parameters.deploy }}', true)
  displayName: deploy to Domonik's Server ;-)
  jobs:
  - job: copy_files_and_docker_up
    displayName: copy Files to Server and start with docker compose
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: $(sshEndpoint)
        contents: '**'
        cleanTargetFolder: true
        cleanHiddenFilesInTarget: true
        overwrite: true
        targetFolder: $(remoteProjectPath)
        isWindowsOnTarget: false
        readyTimeout: '20000'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        dockerComposeFile: '**/docker-compose.yaml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
        arguments: '-d --force-recreate -f $(remoteProjectPath)'
        dockerHostEndpoint: '71430-33034_docker-host'
        currentWorkingDirectory: '$(System.DefaultWorkingDirectory)'
    