parameters:
- name: deploy
  displayName: Deloy Buildartifact
  type: boolean
  default: false

variables:
  remoteProjectPath: /home/felix/projects/mqtt_broker
  sshEndpoint: 71430-33034
  dockerfile: ./eclipse-mosquitto/Dockerfile

trigger:
  branches:
    include:
      - master

pool:
  vimImage: ubuntu-latest

stages:
- stage: build_test
  displayName: Build Image
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: $(dockerfile)
- stage: deploy
  displayName: deploy to Domonik's Server ;-)
  jobs:
  - job: copy_files_and_docker_up
    displayName: copy Files to Server and start with docker compose
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: $(sshEndpoint)
        contents: '**'
        cleanTargetFolder: true
        cleanHiddenFilesInTarget: true
        overwrite: true
        targetFolder: $(remoteProjectPath)
        isWindowsOnTarget: false
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: $(sshEndPoints)
        runOptions: commands
        commands: docker compose -f $(remoteProjectPath)/docker-compose.yaml
        readyTimeout: '20000'