parameters:
- name: deploy
  displayName: Deloy Buildartifact
  type: boolean
  default: false
- name: imagetag
  displayName: Image Tag
  type: object
  default: latest
- name: dockerfiles
  type: object
  default:
    - name: "eclipse_mosquitto"
      file: "./eclipse-mosquitto/Dockerfile"

variables:
  remoteProjectPath: /home/felix/projects/mqtt_broker
  containerRegistryName: LaendleEnergy

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build_test
  displayName: Build Image
  jobs:
  - ${{ each file in parameters.dockerfiles }}:
    - job: build${{ file.name }}
      displayName: Build ${{ file.name }}-Image
      steps:
      - task: Docker@2
        displayName: Build Image
        inputs:
          command: build
          dockerfile: ${{ file.file }}
- stage: build_push
  condition: eq('${{ parameters.deploy }}', true)
  displayName: puild & push to ghcr.io/LaendleEnergy
  jobs:
  - ${{ each file in parameters.dockerfiles }}:
    - job: build_${{ file.name }}
      displayName: Build ${{ file.name }}-Image
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'laendleenergy-acr'
          repository: '${{ file.name }}'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '${{ parameters.imagetag }}'